version: '3.4'

services:
  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 8080:80

  basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development      
    ports:
      - "8081:80"

