version: '3.4'

services:
  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 8080:80

  basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development      
    depends_on:
      - discountdb
    ports:
      - "8081:80"

  discount.api:
    container_name: discount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=123456s!"
    ports:
      - "8082:80"

  discountdb:
    container_name: discountdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456s! 
      - POSGRES_DB=DiscountDb 
    restart: always
    ports:
      - "5440:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
   
 # pgadmin:
    #container_name: pgadmin
    #environment:
    #  - PGADMIN_DEFAULT_EMAIL=igo.pinheiro1@gmail.com
    #  - PGADMIN_DEFAULT_PASSWORD=123456s! 
    #restart: always
    #ports:
    #  - "5050:80"
    #volumes:
    #  - pgadmin_data:/root/.pgadmin
